[project]
name = 'Mental-Health-Support-and-Crisis-Intervention-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mental-health-screening]
path = 'contracts/mental-health-screening.clar'
clarity_version = 2
epoch = 2.5

[contracts.therapy-session-scheduling]
path = 'contracts/therapy-session-scheduling.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
